branches:
  only:
  - master
  - source
language: python
python: 3.5
install: pip install awscli
script:
- aws s3 sync --exclude '.git/*' --exclude 'README.md' --exclude '.travis.yml' --exclude '.gitignore' --exclude '.htaccess' --exclude 'CNAME' --delete . s3://docs.stormpath.com > /dev/null 2>&1
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id E3HQWE1MC4SI62 --paths '/*'
env:
  global:
  - secure: IHVc9WHfKmZGwF2YYXsfsMHjscaSynuNmNpSgKtMkiBZ3kfxp0L2StZpIfUtPP2mlFEVrb0DgOBdXk160v2IIeus112PHAJ0+FjXbgHqdvCqSqke9NLfmxMOO/L0NckJF7LSLN+XLCRYbC3JfXxGqz1CSTYb5QKGOE2Cp7ROyt8=
  - secure: ubrD3ZfipXcNCSm8ispxFTxZHJ8l5hoWsk1tCCFXwg5pQaU+kb6qHr1d6pubcr/YYd7p+ZgfsYU3kh8d80ww+1jktI2YAiTABaw9h/tQ7/QIo//2Uj6fCyX47Y7/d+7c55AJ+SVxs7Z8vsqLModKOICdu6hd/gtpv1L7Hz0afqY=
