# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://docs.stormpath.com
title: Stormpath
subtitle: User Management API for Developers.
author: Stormpath, Inc.
simple_search: http://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user:
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false

# Stormpath docs
sp_docs_menu:
  rest:
    - url: /rest/quickstart
      title: REST API Quickstart Guide
    - url: /rest/product-guide
      title: REST API Product Guide

  java:
    - url: /java/quickstart
      title: Java Quickstart Guide
    - url: /java/product-guide
      title: Java Product Guide
    - url: https://github.com/stormpath/stormpath-sdk-java
      title: Java SDK on GitHub
    - url: https://github.com/stormpath/stormpath-spring-samples
      title: Java Sample App
    - url: https://github.com/stormpath/stormpath-shiro
      title: Apache Shiro Integration
    - url: https://github.com/stormpath/stormpath-shiro-web-sample
      title: Apache Shiro Sample App
    - url: https://github.com/stormpath/stormpath-spring-security
      title: Spring Security Integration
    - url: https://github.com/stormpath/stormpath-spring-security-example
      title: Spring Security Sample App

  php:
    - url: /php/quickstart
      title: PHP Quickstart Guide
    - url: /php/product-guide
      title: PHP Product Guide
    - url: https://github.com/stormpath/stormpath-sdk-php
      title: PHP SDK on GitHub

  ruby:
    - url: /ruby/quickstart
      title: Ruby Quickstart Guide
    - url: /ruby/product-guide
      title: Ruby Product Guide
    - url: https://github.com/stormpath/stormpath-sdk-ruby
      title: Ruby SDK on Github
    - url: https://github.com/stormpath/stormpath-ruby-samples
      title: Ruby Sample Apps
    - url: https://github.com/stormpath/stormpath-rails
      title: Rails Ruby Gem
    - url: https://github.com/stormpath/stormpath-rails-sample
      title: Rails Sample Web App

  python:
    - url: /python/quickstart
      title: Python Quickstart Guide
    - url: /python/product-guide
      title: Python Product Guide
    - url: https://github.com/stormpath/stormpath-sdk-python
      title: Python SDK on GitHub
    - url: https://pypi.python.org/pypi/stormpath-sdk
      title: Python SDK on PyPi
    - url: https://github.com/stormpath/stormpath-python-samples
      title: Python Sample App
    - url: https://github.com/stormpath/stormpath-django
      title: Django Integration

  console:
    - url: /console/quickstart
      title: Stormpath Admin Quickstart Guide
    - url: /console/product-guide
      title: Stormpath Admin Console Guide

# Stormpath docs languages
sp_docs_menu_langs:
  php: PHP
  python: Python
  ruby: Ruby
  java: Java
  rest: REST API
  console: Admin Console
